# LFP & Spike Analysis Pipeline

This repository contains the analysis pipeline for in vivo LFP and spike recordings from freely moving mice during optogenetic stimulation of the serotonergic system. Three tools were used: ChR2, vSWO-5HT1B, and vLWO-5HT1A.

---

## Repository structure

```
├── README.md
│
└── 1_shared/
    ├── common_ingest.py
    ├── experiments_differential_ref_pairs.py
│
└── 2_spikes/
    ├── Functions_preprocessing_spikes.py
    ├── Functions_processing_spikes.py
    ├── preprocessing_spikes.py
    ├── process_spikes_isi.py
    ├── process_spikes_psth.py
    ├── postprocess_spikes_isi_mainfigure.py
    ├── postprocess_spikes_isi_supplement.py
    ├── postprocess_spikes_mua_firing_rate.py
    └── postprocess_spikes_psth_supplement.py
│
└── 3_lfp/
   ├── Functions_preprocessing_lfp.py
   ├── preprocessing_LFP.py
   ├── preprocessing_LFP_CAR.py
   ├── process_lfp_psd.py
   └── process_lfp_fooof.py
│
└── 4_notebooks/
   └── LFP_Pipeline_Example_Notebook.ipynb   # Executable example with synthetic data
   └── Spike_Pipeline_Example_Notebook.ipynb   # Executable example with synthetic data
```

---

## Dependencies

Install all required packages into your Python environment:

```bash
pip install numpy scipy matplotlib pandas specparam tdt
```

Or with conda:

```bash
conda install numpy scipy matplotlib pandas
pip install specparam tdt
```

Tested with Python 3.11, NumPy 2.2, SciPy 1.13, specparam 1.0+.

> **Note:** The `tdt` package requires a Tucker-Davis Technologies system license for data loading. All other pipeline steps run without TDT access.

---

## LFP pipeline — script execution order

Run scripts in the following order for each cohort:

| Step | Script | Purpose |
|------|--------|---------|
| 1 | `experiments_differential_ref_pairs.py` | Define electrode reference pairs and filter settings per animal |
| 2 | `common_ingest.py` | Build `run_manifest.json` for each recording folder |
| 3a | `preprocessing_lfp.py` | Lowpass filter + LMR differential referencing (standard animals) |
| 3b | `preprocessing_lfp_car.py` | Lowpass filter + CAR referencing (floating-reference animals only) |
| 4 | `process_lfp_psd.py` | Welch PSD → Cohen's d → bootstrap CI → group figures |
| 5 | `process_lfp_fooof.py` | specparam parameterization → aperiodic offset/exponent + peak CFs |

> **Note on ChR2 cohort:** Early ChR2 animals (ID0714, ID0895, ID0896) were recorded with a floating reference headstage configuration. These animals are excluded from standard LFP PSD analysis (`preprocessing_lfp.py` filters them automatically via `EXCLUDE_ANIMAL_IDS`) and are instead preprocessed with `preprocessing_lfp_car.py`.

### Path configuration

Each script prompts you to confirm or override the data paths at startup:

```
processing_lfp_psd.py — path configuration
Press Enter to accept the default path shown in brackets.
Processed data root: [C:\Users\...\Data\_Processed]:
Relative cohort path: [Jills_paper\ChR2_cohort\OFT_experimental]:
```

Press **Enter** to use the default, or type a new path.

---

## Spike pipeline — script execution order

| Step | Script | Purpose |
|------|--------|---------|
| 1 | `experiments_differential_ref_pairs.py` | Same as LFP — shared foundation |
| 2 | `common_ingest.py` | Same as LFP — shared foundation |
| 3 | `preprocessing_spikes.py` | Bandpass filter (300–6000 Hz) + threshold-based spike detection |
| 4a | `process_spikes_isi.py` | Inter-spike interval histograms per channel |
| 4b | `process_spikes_psth.py` | Peri-stimulus time histograms + firing rates |
| 5a | `postprocess_spikes_isi_mainfigure.py` | Group ISI + burst fraction Gardner-Altman plot |
| 5b | `postprocess_spikes_mua_firing_rate.py` | MUA firing rate as Gardner-Altman plots per channel with bootstrap CI |
| 5c | `postprocess_spikes_psth_supplement.py` | Full-epoch PSTH with maximum suppression |
| 5d | `postprocess_spikes_isi_supplement.py` | Full distribution ISI |


Steps 4 and 5 can be run in any order.

---

## Notebooks

`LFP_Pipeline_Example_Notebook.ipynb` and `Spike_Pipeline_Example_Notebook.ipynb` provide a step-by-step walkthrough of the complete LFP or spike pipeline using a **synthetically generated example dataset**.

> The example datasets are synthetically generated by Claude (Anthropic) for illustrative purposes. It is not derived from real recordings. The synthetic signals are designed to mimic the statistical properties of real dCA1 LFP data but do not represent actual experimental observations.

To run the notebook:

```bash
conda activate tdt
jupyter notebook notebooks/LFP_Pipeline_Example_Notebook.ipynb
```

---

## Key analysis parameters

| Parameter | Value | Script |
|-----------|-------|--------|
| Raw sampling rate | 24 kHz | — |
| LFP lowpass cutoff | 100 Hz (FIR) | `preprocessing_lfp.py` |
| LFP target sampling rate | 1000 Hz | `preprocessing_lfp.py` |
| Spike bandpass | 300–6000 Hz (Butterworth order 4) | `preprocessing_spikes.py` |
| Spike threshold | 5× MAD | `preprocessing_spikes.py` |
| Welch segment length | 2 s (0.5 Hz resolution) | `process_lfp_psd.py` |
| NLMS step size (µ) | 0.015 | `process_lfp_psd.py` |
| Bootstrap iterations | 5000 | `process_lfp_psd.py` |
| Cohen's d thresholds | small=0.2, medium=0.5, large=0.8 | `process_lfp_psd.py` |
| FOOOF frequency range | 1–100 Hz | `process_lfp_fooof.py` |
| FOOOF aperiodic mode | knee | `process_lfp_fooof.py` |
| Adjusted baseline window | 120 s | all scripts |
| Adjusted stimulation window | 300 s | all scripts |
